#!/bin/sh

if test -f ~/.sbtconfig; then
  . ~/.sbtconfig
fi

JREBEL_HOME=/ewu/jrebel

java -Dfile.encoding=UTF8 -XX:MaxPermSize=256m -Xss2M -Xmx1024M -XX:+CMSClassUnloadingEnabled -XX:+UseConcMarkSweepGC -server -noverify -javaagent:$JREBEL_HOME/jrebel.jar -Drebel.lift_plugin=true -jar `dirname $0`/sbt-launch-0.11.3.jar "$@"
